export enum UserPermission {
    ANONYMOUS = 'ANONYMOUS',
    ADMIN = 'ADMIN',
    EXAM_ENTRY = 'EXAM_ENTRY',
    STUDENT_ENTRY = 'STUDENT_ENTRY',
    EXAM_MARK_ENTRY = 'EXAM_MARK_ENTRY',
    HOSTEL_ATTENDANCE_ENTRY = 'HOSTEL_ATTENDANCE_ENTRY',
    ATTENDANCE_ENTRY = 'ATTENDANCE_ENTRY'
}